// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: key_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           string                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	EncryptionKey []byte                 `protobuf:"bytes,2,opt,name=encryption_key,json=encryptionKey,proto3" json:"encryption_key,omitempty"`  // The symmetric key
	TtlSeconds    int64                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`          // Expiration
	IsReplication bool                   `protobuf:"varint,4,opt,name=is_replication,json=isReplication,proto3" json:"is_replication,omitempty"` // True if this is a server-to-server replication
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterKeyRequest) Reset() {
	*x = RegisterKeyRequest{}
	mi := &file_key_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterKeyRequest) ProtoMessage() {}

func (x *RegisterKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterKeyRequest.ProtoReflect.Descriptor instead.
func (*RegisterKeyRequest) Descriptor() ([]byte, []int) {
	return file_key_service_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterKeyRequest) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *RegisterKeyRequest) GetEncryptionKey() []byte {
	if x != nil {
		return x.EncryptionKey
	}
	return nil
}

func (x *RegisterKeyRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *RegisterKeyRequest) GetIsReplication() bool {
	if x != nil {
		return x.IsReplication
	}
	return false
}

type RegisterKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterKeyResponse) Reset() {
	*x = RegisterKeyResponse{}
	mi := &file_key_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterKeyResponse) ProtoMessage() {}

func (x *RegisterKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterKeyResponse.ProtoReflect.Descriptor instead.
func (*RegisterKeyResponse) Descriptor() ([]byte, []int) {
	return file_key_service_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterKeyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterKeyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           string                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyRequest) Reset() {
	*x = GetKeyRequest{}
	mi := &file_key_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyRequest) ProtoMessage() {}

func (x *GetKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyRequest.ProtoReflect.Descriptor instead.
func (*GetKeyRequest) Descriptor() ([]byte, []int) {
	return file_key_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetKeyRequest) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

type GetKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	EncryptionKey []byte                 `protobuf:"bytes,2,opt,name=encryption_key,json=encryptionKey,proto3" json:"encryption_key,omitempty"` // Returned if not expired
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyResponse) Reset() {
	*x = GetKeyResponse{}
	mi := &file_key_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyResponse) ProtoMessage() {}

func (x *GetKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyResponse.ProtoReflect.Descriptor instead.
func (*GetKeyResponse) Descriptor() ([]byte, []int) {
	return file_key_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetKeyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetKeyResponse) GetEncryptionKey() []byte {
	if x != nil {
		return x.EncryptionKey
	}
	return nil
}

func (x *GetKeyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_key_service_proto protoreflect.FileDescriptor

const file_key_service_proto_rawDesc = "" +
	"\n" +
	"\x11key_service.proto\x12\vkey_service\"\x95\x01\n" +
	"\x12RegisterKeyRequest\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\tR\x03cid\x12%\n" +
	"\x0eencryption_key\x18\x02 \x01(\fR\rencryptionKey\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\x12%\n" +
	"\x0eis_replication\x18\x04 \x01(\bR\risReplication\"I\n" +
	"\x13RegisterKeyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"!\n" +
	"\rGetKeyRequest\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\tR\x03cid\"k\n" +
	"\x0eGetKeyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0eencryption_key\x18\x02 \x01(\fR\rencryptionKey\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xa5\x01\n" +
	"\n" +
	"KeyService\x12R\n" +
	"\vRegisterKey\x12\x1f.key_service.RegisterKeyRequest\x1a .key_service.RegisterKeyResponse\"\x00\x12C\n" +
	"\x06GetKey\x12\x1a.key_service.GetKeyRequest\x1a\x1b.key_service.GetKeyResponse\"\x00B\x1fZ\x1dipfs-file-leaks/key-server/pbb\x06proto3"

var (
	file_key_service_proto_rawDescOnce sync.Once
	file_key_service_proto_rawDescData []byte
)

func file_key_service_proto_rawDescGZIP() []byte {
	file_key_service_proto_rawDescOnce.Do(func() {
		file_key_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_key_service_proto_rawDesc), len(file_key_service_proto_rawDesc)))
	})
	return file_key_service_proto_rawDescData
}

var file_key_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_key_service_proto_goTypes = []any{
	(*RegisterKeyRequest)(nil),  // 0: key_service.RegisterKeyRequest
	(*RegisterKeyResponse)(nil), // 1: key_service.RegisterKeyResponse
	(*GetKeyRequest)(nil),       // 2: key_service.GetKeyRequest
	(*GetKeyResponse)(nil),      // 3: key_service.GetKeyResponse
}
var file_key_service_proto_depIdxs = []int32{
	0, // 0: key_service.KeyService.RegisterKey:input_type -> key_service.RegisterKeyRequest
	2, // 1: key_service.KeyService.GetKey:input_type -> key_service.GetKeyRequest
	1, // 2: key_service.KeyService.RegisterKey:output_type -> key_service.RegisterKeyResponse
	3, // 3: key_service.KeyService.GetKey:output_type -> key_service.GetKeyResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_key_service_proto_init() }
func file_key_service_proto_init() {
	if File_key_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_key_service_proto_rawDesc), len(file_key_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_key_service_proto_goTypes,
		DependencyIndexes: file_key_service_proto_depIdxs,
		MessageInfos:      file_key_service_proto_msgTypes,
	}.Build()
	File_key_service_proto = out.File
	file_key_service_proto_goTypes = nil
	file_key_service_proto_depIdxs = nil
}
